name = "dbce"
compatibility_date = "2024-04-03"
pages_build_output_dir = "./build/client"


[[env.production.durable_objects.bindings]]
name = "do"
class_name = "MyDurableObject"
script_name = "auth-do"

[env.production]
compatibility_date = "2024-04-03"

[dev]
port = 8080
