#:schema node_modules/wrangler/config-schema.json
name = "auth-do"
main = "src/index.ts"
compatibility_date = "2024-04-05"


[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"


[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]

